# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  # General
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-case-conflict
      - id: detect-private-key
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: check-yaml
      - id: pretty-format-json
        args:
          - --autofix
          - --indent=4
          - --no-sort-keys
      - id: check-added-large-files
      - id: check-merge-conflict

  # Secrets
  - repo: https://github.com/awslabs/git-secrets
    rev: 80230afa8c8bdeac766a0fece36f95ffaa0be778
    hooks:
      - id: git-secrets
        entry: git-secrets --scan
        files: .

  # CloudFormation
  - repo: https://github.com/aws-cloudformation/cfn-python-lint
    rev: v0.37.1
    hooks:
      - id: cfn-python-lint
        name: AWS CloudFormation Linter
        files: \.(template)$
        args: []

  # Python
  - repo: https://github.com/pycqa/pylint
    rev: pylint-2.6.0
    hooks:
      - id: pylint
        args:
          - --errors-only

  - repo: https://github.com/PyCQA/isort
    rev: 5.5.4
    hooks:
      - id: isort
